### ISSUE TITLE
県公開情報に合わせ入院状況の個別把握を削除

### ISSUE THREAD

**Issue by Matthew6186** [ta1m1kam/shimane-covid19#122]
## 起こっている問題 / The Problem
- どこかのタイミングで、県の公開情報から個別患者が退院したかどうかが非公開となりました。
    - https://www.pref.shimane.lg.jp/medical/yakuji/kansensyo/other/topics/bukan2020.html
- こちらのサイト側でも、陽性患者の退院ステータスを非公開に変更するべきです。

## 期待する見せ方・挙動 / Expected Behavior
- 陽性患者の属性テーブルから、退院ステータスを削除

## 起こっている問題の再現手段 / Steps to Reproduce
1. https://shimane-covid19.netlify.app/ にアクセス
2. 「陽性患者の属性」カード内のテーブルの「退院」欄を確認

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by ta1m1kam** [comment]
こちらもバグではないので外します

**Comment by ta1m1kam** [comment]
こちら、一旦注意書きで対応したいです。
退院ステータスは以前の情報から確認ができているもの(松江市のHPに本人同意ありのもの)なので、
> ※ 確認ができているもののみ記載

のような形が良いと思いましたがどうでしょうか？

県のサイトも今は非公開ですが、また公開される可能性があるので:bow:

**Comment by ta1m1kam** [comment]
> 県のサイトも今は非公開ですが、また公開される可能性があるので

これはないかもしれないですね。プライバシーの観点を県も市も気にしているように見えるので、
退院ステータスは消す方向が良いかもしれませんね。（意見が転々としてすみません）

その上で、市ごとに退院と入院のステータス見れるようにしたいですね

**Comment by Matthew6186** [comment]
> 退院ステータスは以前の情報から確認ができているもの(松江市のHPに本人同意ありのもの)なので、
> ※ 確認ができているもののみ記載
> のような形が良いと思いましたがどうでしょうか？

注意書きの記載で対応の形で良いと思います。
若干の懸念点としては、退院ステータスの1次ソースが島根県ではなく松江市となるので、そこの誤解が生じないようにしたほうがよさそうです。
例えば、
※ 市町村が公表しているもののみ記載
という書き方にするのはどうでしょうか。
