### ISSUE TITLE
検査陽性者の状況を県公開の療養状況に合わせる

### ISSUE THREAD

**Issue by Matthew6186** [ta1m1kam/shimane-covid19#123]
## 起こっている問題 / The Problem
- どこかのタイミングで、県が公開する陽性患者の療養状況の公表形式が変更になりました
    - https://www.pref.shimane.lg.jp/medical/yakuji/kansensyo/other/topics/bukan2020.html
- こちらのサイト側でも、県のフォーマットに合わせた表示に変更が必要です

## 期待する見せ方・挙動 / Expected Behavior
- 「検査陽性者の状況」のカードを、県公開のフォーマットで表示されるよう変更する

## 起こっている問題の再現手段 / Steps to Reproduce
1. https://shimane-covid19.netlify.app/ にアクセス
2. 「検査陽性者の状況」カード内のテーブルを確認

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by Matthew6186** [comment]
とりあえずこっちの表示から直します

**Comment by ta1m1kam** [comment]
バグではないので、bugラベル外します。
