### ISSUE TITLE
県内各所のお知らせのリンク切れ対応

### ISSUE THREAD

**Issue by Matthew6186** [ta1m1kam/shimane-covid19#77]
## 起こっている問題 / The Problem
- 県内各所のお知らせ（place-news）のリンクが機能していない
- 現在表示されている3項目とも、リンク先が( https://shimane-covid19.netlify.app/place-news/item.url )となっている

## 期待する見せ方・挙動 / Expected Behavior
- 各機関の最新の周知ページにリンクするようURLを修正する

## 起こっている問題の再現手段 / Steps to Reproduce
1. 「県内各所のお知らせ」ページにアクセス
2. 任意のURLをクリック
3. 「このページはご利用いただけません」のエラーページが表示

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by ta1m1kam** [comment]
だんだんです:bow:
