### ISSUE TITLE
県内各所のお知らせページの内容見直しの提案

### ISSUE THREAD

**Issue by Matthew6186** [ta1m1kam/shimane-covid19#79]
## 改善詳細 / Details of Improvement
- 「県内各所のお知らせ」に記載の内容について、県内の主要な機関を網羅できていないと考えている。
- 5/31までの緊急事態宣言延長という現状を踏まえ、「県内各所のお知らせ」を見直したい
- 見直し方針はこのIssueのコメント欄で議論の上、修正のためのIssueを改めて作ることとしたい

## 期待する見せ方・挙動 / Expected behavior
- 緊急事態宣言の解除→経済活動の再開のステップで、県民にとって必要十分な内容となるようにしたい

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by Matthew6186** [comment]
# 修正目途
- 緊急事態宣言の見直しタイミングとされる5/14までには修正反映したいです。
- 5/10頃が修正方針の決定目途か？と思います。

# 修正案

## 1.厚労省方針（緊急事態宣言時に事業の継続が求められる事業者）に沿った一覧に増やす

- ( https://www.mhlw.go.jp/content/10900000/000627560.pdf )別紙P30の「３．国民の安定的な生活の確保」に記載の10事業者からのお知らせを記載
- 【メリット】厚労省方針に沿った情報の集約が可能
- （デメリット）情報過多により可読性が低下する恐れあり
- （デメリット）URL変更によるページの更新負荷が増大

## 2. 外部の情報集約ページへのリンクとする

- 例えば、山陰中央新報社の新型コロナ特集ページ( https://www.sanin-chuo.co.jp/www/genre/1000100000064/index.html )のリンクとする
    - リンク先ページのリンク規定に準拠する必要あり
- 【メリット】情報更新にかかる作業負荷が軽減
- （デメリット）経済再開に向けた情報が将来的に掲載されるかは不明

## 3. 県内各所のお知らせページの廃止

- 個別事業者の情報については対策サイトとして扱わない方針とする
- 【メリット】情報更新が不要になる
- （デメリット）県内事業者による事業再開に向けた動きがサイト内で見えなくなる
- （デメリット）自治体側からの情報では網羅できない内容を記載する場所が無くなる

# ご相談

- 一旦、上記3案を軸に議論できればと思います。他にも修正案や考え方があればここでコメントしてください。

**Comment by ta1m1kam** [comment]
３番でいいかもしれないです。
Google analyticsでページルーティングの訪問者数を見ると、`/place-news`へのアクセスはほとんどないので0.3%くらい。
基本的に来る訪問者の目的はルートページなので、このサイトへ訪問している人は、検査状況と陽性者属性を見るのが目的だと思われるのでなくして良さそうです。

**Comment by ta1m1kam** [comment]
代わりに、県内事業者へのリンクでも良さそうと思いました。
厚生労働省のページよりは、島根県庁のページが良いと思います。
https://www.pref.shimane.lg.jp/bousai_info/bousai/kikikanri/shingata_taisaku/kigyou_jigyousha.html

**Comment by Matthew6186** [comment]
@TaigaMikami リアクションありがとうございます。
私も、現実的には2番か3番かどちらかと思っていたのですが、アクセス状況踏まえると3番で良さそうですね。情報ありがとうございました。

**Comment by Matthew6186** [comment]
@TaigaMikami 代わりに入れるURLについてちょっと議論しておきたいのですが、県内事業者向けのリンクを確認している過程で、下記の島根県庁ページに各種周知リンクがまとまっているのを見つけました。
https://www.pref.shimane.lg.jp/bousai_info/bousai/kikikanri/shingata_taisaku/new_coronavirus_portal.html
→分野別情報

この一覧から何個か選んでリンクを作るか、もしくは直接このページに飛ばしてしまうのもありかなと。
ただ直接ページに飛ばす際はタグが付けられてないので、ダイレクトに分野別情報の欄に飛ばせないのがちょっとややこしいですが。

**Comment by Matthew6186** [comment]
昨日5/7から、山陰両県で外出自粛が緩和され始めているため、本件対応始めます。
